services:
  db:
    image: postgres:15
    container_name: blog_db
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

  app:
    build: .  # instacopyフォルダ直下のDockerfileを読み込む
    container_name: instacopy_app
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/blog_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  web:
    image: nginx:latest
    container_name: instacopy_web
    ports:
      - "9080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
